### ISSUE TITLE
Add hover state to all video players

### ISSUE THREAD

**Issue by steve-schultz** [theberrics/html5-skin#4]
Overlay black at 60% opacity. Ease-in and Ease-out.

**Comment by boxyardboy** [comment]
@steve-schultz 

Hey man, just to be clear ... you want to add a hover state to the "start screen state" (unplayed state), correct?

So, the overlay should appear above the cover image, but below the play button, correct?

Thanks!!!

**Comment by steve-schultz** [comment]
Correct

On Thu, Jul 14, 2016 at 11:03 AM, boxyardboy notifications@github.com
wrote:

> @steve-schultz https://github.com/steve-schultz
> 
> Hey man, just to be clear ... you want to add a hover state to the "start
> screen state" (unplayed state), correct?
> 
> So, the overlay should appear above the cover image, but below the play
> button, correct?
> 
> Thanks!!!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/theberrics/html5-skin/issues/4#issuecomment-232744163,
> or mute the thread
> https://github.com/notifications/unsubscribe/ARclPBBB-wUq_WMRteNtaWO0m91uc_Z1ks5qVnnvgaJpZM4I6NzB
> .

## 

[image: The Berrics] http://theberrics.com/
Steve Schultz
Web Designer

_theberrics.com http://theberrics.com/_

**Comment by boxyardboy** [comment]
done
